### ISSUE TITLE
Error Message "Please upload files before sending the form."

### ISSUE THREAD

**Issue by taunusweb** [fnagel/mailfiles#2]
I get this error, when using mailfiles in TYPO3 8.7LTS. Pluploadfe works fine, the file is added to the Backend, but no mail is sent.  "mailFrom" and "mailTo " in plugin.tx_mailfiles_pi1.settings is set to real values.
Any Idea?
Thanks 
Uli

**Comment by fnagel** [comment]
Hey Uli, 

mhh, that should work without any further configuration. 

Do mails work in general (try with the mail test in install tool)? 
Did you take a look in the log?
Did you enable debug mode in the install tool?

You probably need to debug that in the controller...

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by taunusweb** [comment]
Uuh, sorry, this question is not relevant anymore, I think we cancelled this feature, so I can't tell you more about it....

**Comment by fnagel** [comment]
Ok. Thanks for the feedback.
