### ISSUE TITLE
Option to send the files to any e-mail address

### ISSUE THREAD

**Issue by wowaTYPO3** [fnagel/mailfiles#4]
It would be cool if you had the option to enter any e-mail address as a recipient in the frontend.
This feature could perhaps be switched on/off.
Then the extension could be a real alternative to tools like WeTransfer or similar.

**Comment by fnagel** [comment]
Hi @wowaTYPO3, thanks for the suggestion and the introduction in your Twitch channel :-) Both is highly appreciated!

I've added a PR here: https://github.com/fnagel/mailfiles/pull/5 Please take a look and give feedback if this works out for you! 
You need to enable the `settings.showMailToField` configuration in TS.

FYI: @ErHaWeb

**Comment by fnagel** [comment]
@wowaTYPO3 Please note my comments on YouTube regarding upload limit and jQuery: https://www.youtube.com/watch?v=uzh8jgCqI5g

**Comment by wowaTYPO3** [comment]
Sorry, can't see any comments on YouTube?

**Comment by fnagel** [comment]
I've posted it twice... any idea why the comments are removed or hidden? I've posted it again: https://www.youtube.com/watch?v=uzh8jgCqI5g&lc=UgyL7vY7Aajlbafr95t4AaABAg

**Comment by fnagel** [comment]
..and its gone again... WTF

**Comment by fnagel** [comment]
...and its gone again. Unsure why. Probably its too long or the links are a problem.

BackUp: https://bin.felixnagel.com/?8e35eee38428f330#5btiH2z3yF9GftWDL6mq9hWD5x1ubgU9tASFXKbANNzy

**Comment by wowaTYPO3** [comment]
Sorry, I don't even see them in the moderation view. Apparently YouTube has problems with some terms?

**Comment by wowaTYPO3** [comment]
But sending to any address works ;)

**Comment by fnagel** [comment]
Ok, tried again to comment on YT, in smaller chunks and without links. Seems to work. Full comment see paste bin link above!

**Comment by fnagel** [comment]
@wowaTYPO3 Thanks for the feedback! PR has been merged and will be included in the next TER release :-)
